# Generated by Django 3.0.3 on 2020-09-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('blood_group', models.CharField(choices=[('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('AB Positive', 'AB Positive'), ('AB Negative', 'AB Negative')], default='A Positive', max_length=20)),
                ('special_mark', models.CharField(blank=True, max_length=120, null=True)),
                ('age', models.CharField(blank=True, max_length=120, null=True)),
                ('skin_tone', models.CharField(blank=True, max_length=120, null=True)),
                ('dress_up', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_location', models.CharField(blank=True, max_length=150, null=True)),
                ('miscellaneous', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'people_information',
            },
        ),
    ]
