# Generated by Django 3.0.3 on 2020-09-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200913_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='miscellaneous',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
