# Generated by Django 3.0.3 on 2020-09-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200913_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='people',
            name='nick_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
