# Generated by Django 3.0.3 on 2020-09-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200913_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='gardian_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='gardian_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
