# Generated by Django 3.0.7 on 2020-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_people_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='search/')),
            ],
        ),
    ]
